myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls')),
]

project/urls.py
from django.urls import path

from . import views

app_name='project'
urlpatterns=[
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/',views.DetailView.as_view(), name='detail'),
    path('<int:pk>/change/',views.changeView.as_view(), name='change'),
]

project/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    author=models.ForeignKey('Author', on_delete=models.CASCADE)
    book_name=models.CharField(max_length=200)
    pub_date=models.DateTimeField('Year of issue')
    edition=models.CharField(max_length=200)
    genre=models.CharField(max_length=100)
    def __str__(self):
        return self.book_name

class Author(models.Model):
    author_name=models.CharField(max_length=100)
    country_of_birth=models.CharField(max_length=50)
    year_of_birth=models.CharField(max_length=15)
    def __str__(self):
        return self.author_name

project/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Book, Author

# Create your views here.
class IndexView(generic.ListView):
    template_name='project/index.html'
    context_object_name='latest_book_list'

    def get_queryset(self):
        return Book.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model=Book
    template_name='project/detail.html'

class changeView(generic.DetailView):
    model=Book
    template_name='project/changes.html'
    
def index(request):
    latest_book_list=Book.objects.order_by('-pub_date')[:5]
    template=loader.get_template('project/index.html')
    context={'latest_book_list':latest_book_list,}
    return HttpResponse(template.render(context,request))

def detail(request, book_id):
    book=get_object_or_404(Book,pk=book_id)
    return render(request,'project/detail.html',{'book':book})

def change_book(request, book_id):
    book=get_object_or_404(Book,pk=book_id)
    book.book_name=book.book_name+' test'
    book.save()
    return HttpResponseRedirect(reverce('project:detail', args=(book_id,)))

project/templates/project/changes.html
<h1>{{ book.book_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'project:change' book.id %}" method="post">
{% csrf_token %}
{% for change in book.change_set.all %}
    <input type="project" name="change" id="change{{ forloop.counter }}" value="{{ change.id }}">
    <label for="change{{ forloop.counter }}">{{ change.change_name }}</label><br>
{% endfor %}
<input type="submit" value="Save">
</form>

project/templates/project/detail.html
<h1>{{ book.book_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'project:change' book.id %}" method="post">
{% csrf_token %}
{% for change in book.all %}
    <input type="project" name="change" id="change{{ forloop.counter }}" value="{{ change.id }}">
    <label for="change{{ forloop.counter }}">{{ change.change_name }}</label><br>
{% endfor %}
<input type="submit" value="change">
</form>

project/templates/project/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'project/style.css' %}">

{% if latest_book_list %}
    <ul>
    {% for book in latest_book_list %}
        <li><a href="{% url 'project:detail' book.id %}">{{ book.book_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No project are avaiable.</p>
{% endif %}